
import './globals.css'
import { Inter } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
import { NaviMenu } from './dashboard/navigation-menu'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

<head>
   <meta http-equiv="Content-Security-Policy" content="connect-src http:"  />
      </head>

      <body className={inter.className}>


       {children}
        <Toaster/>

      </body>
    </html>
  )
}
