'use client'
import { Inter } from 'next/font/google'
import { NaviMenu } from './navigation-menu'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={inter.className}>

              <NaviMenu />

        <div> {children}</div>

      </body>
    </html>
  )
}
